site_name: Nova
nav:
  - Home: index.md
  - README: readme.md
  - Contributing: contributing.md
  - Storage: STORAGE.md
  - Architecture: ARCHITECTURE.md
  - Migration: MIGRATION.md
  - GH-Pages: GH-PAGES-README.md
theme:
  name: material
repo_url: https://github.com/Yinhang3377/Nova
site_dir: site