[package]
name = "nova-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
log = "0.4"
rand = "0.8"
sha2 = "0.10"

[dev-dependencies]
serde_json = "1.0"
