[package]
name = "nova-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1", features = ["derive"] }
anyhow = "1.0"
nova-core = { path = "../nova-core" }
hex = "0.4"
serde_json = "1.0"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "2.1"
