name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config
      - name: Build workspace
        run: cargo build --workspace --release
      - name: Run demo binary
        run: |
          # run the CLI demo which should invoke nova_core::wallet::send
          cargo run -p nova-cli --release --manifest-path nova-cli/Cargo.toml -- simulate --count 1 || true
      - name: Run wallet demo
        run: |
          # explicitly run the wallet send demo so nova-core prints Chinese lines
          cargo run -p nova-cli --release --manifest-path nova-cli/Cargo.toml -- wallet send || true
