name: CI

on:
  push:
    branches: [ "main", "design/scaffold" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain-action@stable
      - name: Cache cargo registry and index
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: cargo fmt
        run: cargo fmt --all -- --check
      - name: cargo clippy
        run: cargo clippy --all -- -D warnings
      - name: cargo test
        run: cargo test --workspace --no-fail-fast
      - name: Validate CLI simulate runs in CI
        run: cargo run -p nova-cli -- simulate --count 1 --json
