name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install deps
        run: sudo apt update && sudo apt install -y libssl-dev pkg-config build-essential

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test -- --nocapture
