name: Docs smoke-test on gh-pages

on:
  push:
    branches:
      - gh-pages

permissions:
  contents: read
  issues: write

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check site responds 200
        id: curl
        run: |
          set -euo pipefail
          URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
          echo "Checking $URL"
          status=$(curl -s -o /dev/null -w "%{http_code}" "$URL") || true
          echo "status=$status" >> $GITHUB_OUTPUT
          if [ "$status" -ne 200 ]; then
            echo "Site returned $status" >&2
            exit 1
          fi

      - name: Check page content for MkDocs fingerprint
        run: |
          URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
          content=$(curl -sL "$URL")
          echo "$content" | grep -q "mkdocs-" || (echo "mkdocs fingerprint not found" >&2; exit 1)

  report-issue:
    needs: smoke-test
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Create issue on failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TITLE="Docs smoke-test failure for ${{ github.repository }}"
          BODY="The smoke-test for the GitHub Pages site failed on commit ${{ github.sha }}.\n\nSee the workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "Creating issue: $TITLE"
          curl -s -S -X POST -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" \
            "$GITHUB_API_URL/repos/${{ github.repository }}/issues" -d @- <<EOF || true
          { "title": "$TITLE", "body": "$BODY", "labels": ["docs","smoke-test-failure"] }
          EOF
