name: docs: build & deploy

on:
  push:
    branches: [ main ]
    tags: ['v*']

permissions:
  contents: write

jobs:
  link-check:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Link check with lychee
        uses: lycheeverse/lychee-action@v1
        with:
          glob: 'docs/**/*.md'

  spell-check:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run spell check
        uses: check-spelling/action@v0.0.22
        # default config will run; maintainers can add wordlists in .github/wordlists

  build-deploy:
    runs-on: ubuntu-latest
    needs: [link-check, spell-check]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Build site
        run: mkdocs build --strict

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          keep_files: false
