name: Publish MkDocs to gh-pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build MkDocs and publish
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Build MkDocs site
        run: |
          if [ -f mkdocs.yml ]; then
            mkdocs build --site-dir site
          else
            echo "mkdocs.yml not found 鈥?skipping build"
            mkdir -p site
            echo "<html><body><h1>Docs placeholder</h1></body></html>" > site/index.html
          fi

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # If you supply a personal access token (secrets.PAGES_TOKEN) it will be used.
          # Otherwise the action will use the github_token input (GITHUB_TOKEN). Keep them separate
          # so we don't accidentally pass GITHUB_TOKEN into personal_token.
          personal_token: ${{ secrets.PAGES_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
